---
mongo:
    image: mongo

redis:
    image: redis

api:
    image: n4sjamk/teamboard-api
    links:
        - mongo
        - redis
        - img
    environment:
        - NODE_ENV=production
        - PORT=9002
        - TOKEN_SECRET=hard_codaus_on_parasta
        - MONGODB_URL=mongodb://mongo:27017/production
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - IMG_URL=http://img:9003/img
    expose:
        - "9002"
    command: "/usr/bin/node /home/teamboard/teamboard-api/index.js"
    restart: "on-failure:10"

io:
    image: n4sjamk/teamboard-io
    links:
        - redis
        - api
    environment:
        - NODE_ENV=production
        - PORT=9001
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - API_URL=http://api:9002/api
    expose:
        - "9001"
    command: "/usr/bin/node /home/teamboard/teamboard-io/index.js"
    restart: "on-failure:10"

client:
    image: n4sjamk/teamboard-client
    environment:
        - NODE_ENV=production
        - API_URL=${api_url}
        - IO_URL=${io_url}
    restart: "on-failure:10"

img:
    image: n4sjamk/teamboard-img
    links:
        - mongo
    environment:
        - NODE_ENV=production
        - PORT=9003
        - MONGO_URL=mongodb://mongo:27017/production

haproxy:
    image: n4sjamk/teamboard-haproxy
    links:
        - api
        - io
        - client
        - img
    ports:
        - "80:80"

