<?php
// Automatically Generated by TestLink Installer - Mon, 05 Sep 16 13:10:50 +0300
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'root');
define('DB_HOST', 'mysql');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
